export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_ERROR_LOCATION = 'GET_ERROR_LOCATION';
export const GET_LOADING_LOCATION = 'GET_LOADING_LOCATION';

export const POST_LOCATION = 'POST_LOCATION';
export const POST_ERROR_LOCATION = 'POST_ERROR_LOCATION';

