import '@/styles/globals.css'
import Layout from '../components/Layout';
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { red } from '@mui/material/colors'
import NextNProgress from 'nextjs-progressbar';
import Head from 'next/head';
import { GlobalState } from '@/providers/GlobalState';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const theme = createTheme({
  palette: {
    primary: {
      main: red[400],
    },
  },
});

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Water quality monitoring system on different locations using IoT || Mobile & Pervasive Computing Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalState>
        <ThemeProvider theme={theme}>
          <ToastContainer autoClose={2000} />
          <Layout>
            <NextNProgress color='white' height={4} />
            <Component {...pageProps} />
          </Layout>
        </ThemeProvider>
      </GlobalState>
    </>
  )
}
