import '@/styles/globals.css'
import Layout from '../components/Layout';
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { red } from '@mui/material/colors'
import NextNProgress from 'nextjs-progressbar';
import Head from 'next/head';

export const theme = createTheme({
  palette: {
    primary: {
      main: red[400],
    },
  },
});

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Water quality monitoring system on different locations using IoT || Mobile & Pervasive Computing Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <Layout>
          <NextNProgress color='white' />
          <Component {...pageProps} />
        </Layout>
      </ThemeProvider>
    </>
  )
}
