export const GET_SENSORS = 'GET_SENSORS';
export const GET_ERROR_SENSOR = 'GET_ERROR_SENSOR';
export const GET_LOADING_SENSOR = 'GET_LOADING_SENSOR';

export const POST_SENSORS = 'POST_SENSOR';
export const POST_ERROR_SENSOR = 'POST_ERROR_SENSOR';
export const POST_SENSOR_RESET = 'POST_SENSOR_RESET'

export const DELETE_SENSOR = 'DELETE_SENSOR';
export const DELETE_ERROR_SENSOR = 'DELETE_ERROR_SENSOR';
export const DELETE_SENSOR_RESET = 'DELETE_SENSOR_RESET'